"Type: Bug":
  - 'Bug'
"Type: Chore":
  - 'Chore'
"Type: Docs":
  - 'Docs'
"Type: Feature":
  - 'Feature'
"Type: Question":
  - 'Question'
"Priority: Critical":
  - 'Priority: Urgent'
"Priority: High":
  - 'Priority: High'
"Priority: Medium":
  - 'Priority: Normal'
"Priority: Low":
  - 'Priority: Low'
