local monarch = require "monarch.monarch"
local json = require "wortal.utils.json"
local popup = require "examples.apis.popup.popup"

function init(self)
	msg.post("#", "initialize")
	msg.post("@render:", "clear_color", { color = vmath.vector4(0.1, 0.1, 0.1, 1.0) })
end

function update(self, dt)
end

function on_message(self, message_id, message, sender)
	if message_id == hash("initialize") then
		monarch.show(hash("overview"))
	end
end
